spring:
  main:
    allow-bean-definition-overriding: 'true'
    scan:
      base-packages: org.saga.example.delivery
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: 'true'
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5432/delivery
cloud:
  aws:
    credentials:
      useDefaultAwsCredentialsChain: 'true'

      instanceProfile: 'false'
    region:
      static: ap-south-1
    stack:
      auto: 'false'
server:
  port: '8083'

