cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
      instanceProfile: 'false'
      useDefaultAwsCredentialsChain: 'true'
    region:
      static: ap-south-1
    end-point:
      urihttps: //sqs.ap-south-1.amazonaws.com/471112708089/payment-updates
    stack:
      auto: 'false'
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/order
    password: root
  jpa:
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  main:
    allow-bean-definition-overriding: 'true'
    scan:
      base-packages: org.saga.example.order
